/**
 * Latvian localization for Clerk components (Zoptero)
 * -----------------------------------------------
 * Ensures all Clerk UI is in Latvian, including sign-in titles.
 * Format matches Clerk's localization prop requirements.
 */
export const clerkLocalization = {
  signIn: {
    title: 'Ienāgt Zoptero',
    subtitle: 'Pierakstīties ar',
    start: {
      title: 'Ienākt Zoptero',
      subtitle: 'Pierakstīties ar',
      titleCombined: 'Ienākt Zoptero',
      subtitleCombined: 'Pierakstīties ar',
    },
    socialButtons: {
      google: 'Google',
      facebook: 'Facebook',
      apple: 'Apple',
      microsoft: 'Microsoft',
      github: 'GitHub',
      linkedin: 'LinkedIn',
    },
  },
  dividerText: 'vai',
  formButtonPrimary: 'Ienākt platformā',
  formButtonSecondary: 'Reģistrēties',
  formButtonGoogle: 'Google',
  formButtonFacebook: 'Facebook',
  formButtonApple: 'Apple',
  formButtonMicrosoft: 'Microsoft',
  formButtonGitHub: 'GitHub',
  formButtonEmail: 'E-pasts',
  formButtonPassword: 'Parole',
  formButtonCode: 'Kods',
  formButtonNext: 'Nākamais',
  formButtonBack: 'Atpakaļ',
  formButtonResendCode: 'Atsūtīt kodu vēlreiz',
  formButtonResendCodeIn: 'Atsūtīt kodu vēlreiz pēc {{seconds}}s',
  formButtonSendCode: 'Sūtīt kodu',
  formButtonVerify: 'Pārbaudīt',
  formButtonContinue: 'Turpināt',
  formButtonSubmit: 'Iesniegt',
  formButtonCancel: 'Atcelt',
  formButtonForgotPassword: 'Aizmirsāt paroli?',
  formButtonSignUp: 'Reģistrēties',
  formButtonSignIn: 'Ienākt',
  formButtonUpdate: 'Atjaunināt',
  formButtonDelete: 'Dzēst',
  formButtonEdit: 'Rediģēt',
  formButtonSave: 'Saglabāt',
  formButtonClose: 'Aizvērt',
  formButtonOpen: 'Atvērt',
  formButtonView: 'Skatīt',
  formButtonDownload: 'Lejupielādēt',
  formButtonUpload: 'Augšupielādēt',
  formButtonCopy: 'Kopēt',
  formButtonPaste: 'Ielīmēt',
  formButtonCut: 'Izgriezt',
  formButtonSelect: 'Izvēlēties',
  formButtonClear: 'Notīrīt',
  formButtonReset: 'Atiestatīt',
  formButtonSearch: 'Meklēt',
  formButtonFilter: 'Filtrēt',
  formButtonSort: 'Kārtot',
  formButtonGroup: 'Grupēt',
  formButtonExpand: 'Izvērst',
  formButtonCollapse: 'Sakļaut',
  formButtonShow: 'Rādīt',
  formButtonHide: 'Slēpt',
  formButtonEnable: 'Aktivēt',
  formButtonDisable: 'Deaktivēt',
  formButtonInstall: 'Instalēt',
  formButtonUninstall: 'Atinstalēt',
  formButtonUpdateAvailable: 'Pieejama atjauninājuma versija',
  formButtonInstallUpdate: 'Instalēt atjauninājumu',
  formButtonRestart: 'Pārstartēt',
  formButtonShutdown: 'Izslēgt',
  formButtonRestartLater: 'Pārstartēt vēlāk',
  formButtonRestartNow: 'Pārstartēt tagad',
  formButtonRestartRequired: 'Nepieciešams pārstartēšana',
  formButtonRestartRequiredTitle: 'Nepieciešams pārstartēšana',
  formButtonRestartRequiredMessage: 'Lai pārņemtu šo izmaiņu, jums ir jāpārstartē aplikācija.',
  formButtonRestartRequiredAction: 'Pārstartēt tagad',
  formButtonRestartRequiredCancel: 'Atcelt',
  formButtonRestartRequiredLater: 'Pārstartēt vēlāk',
};